"""
knowledge_base.py — Curated Q&A knowledge for training the libaix classifier.

Organizes knowledge into *domains* (networking, internet, intranet, security, …).
Each entry is a (question/query, answer, domain_tag) triple.
New domains can be added by extending KNOWLEDGE or loading external JSON.
"""

from __future__ import annotations

import json
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────
# Knowledge entries: (question, answer, domain)
# ──────────────────────────────────────────────────────────────────────

KNOWLEDGE: list[tuple[str, str, str]] = [
    # ── NETWORKING (OSI, TCP/IP, protocols) ───────────────────────────
    ("What is the OSI model?",
     "The OSI (Open Systems Interconnection) model is a 7-layer framework that standardizes network communication: Physical, Data Link, Network, Transport, Session, Presentation, and Application.",
     "networking"),
    ("What are the 7 layers of the OSI model?",
     "Layer 1: Physical, Layer 2: Data Link, Layer 3: Network, Layer 4: Transport, Layer 5: Session, Layer 6: Presentation, Layer 7: Application.",
     "networking"),
    ("What is TCP?",
     "TCP (Transmission Control Protocol) is a connection-oriented transport layer protocol that provides reliable, ordered delivery of data between applications using a three-way handshake.",
     "networking"),
    ("What is UDP?",
     "UDP (User Datagram Protocol) is a connectionless transport layer protocol that sends datagrams without establishing a connection, offering low latency but no delivery guarantees.",
     "networking"),
    ("What is the difference between TCP and UDP?",
     "TCP is connection-oriented with guaranteed delivery and ordering; UDP is connectionless with no delivery guarantee but lower latency. TCP is used for web/email; UDP for streaming/gaming.",
     "networking"),
    ("What is an IP address?",
     "An IP address is a unique numerical label assigned to each device on a network. IPv4 uses 32-bit addresses (e.g. 192.168.1.1); IPv6 uses 128-bit addresses.",
     "networking"),
    ("What is a subnet mask?",
     "A subnet mask divides an IP address into network and host portions. For example, 255.255.255.0 (/24) means the first 24 bits identify the network and the last 8 bits identify hosts.",
     "networking"),
    ("What is DNS?",
     "DNS (Domain Name System) translates human-readable domain names (like google.com) into IP addresses that computers use to route traffic.",
     "networking"),
    ("What is DHCP?",
     "DHCP (Dynamic Host Configuration Protocol) automatically assigns IP addresses, subnet masks, gateways, and DNS servers to devices on a network.",
     "networking"),
    ("What is a MAC address?",
     "A MAC (Media Access Control) address is a unique 48-bit hardware identifier assigned to a network interface card (NIC), written as six hex pairs like AA:BB:CC:DD:EE:FF.",
     "networking"),
    ("What is a router?",
     "A router is a Layer 3 device that forwards packets between different networks by examining destination IP addresses and using routing tables.",
     "networking"),
    ("What is a switch?",
     "A network switch is a Layer 2 device that forwards frames within a LAN by learning MAC addresses and building a forwarding table.",
     "networking"),
    ("What is ARP?",
     "ARP (Address Resolution Protocol) maps IP addresses to MAC addresses on a local network, allowing Layer 2 frame delivery.",
     "networking"),
    ("What is a VLAN?",
     "A VLAN (Virtual LAN) logically segments a physical network at Layer 2, isolating broadcast domains without requiring separate hardware.",
     "networking"),
    ("What is NAT?",
     "NAT (Network Address Translation) maps private IP addresses to a public IP, allowing multiple devices to share one public address for internet access.",
     "networking"),
    ("What is a firewall?",
     "A firewall monitors and filters network traffic based on security rules, blocking unauthorized access while permitting legitimate communication.",
     "networking"),
    ("What is a gateway?",
     "A gateway is a node that serves as an access point between two networks, often the router that connects a LAN to the internet.",
     "networking"),
    ("What is ICMP?",
     "ICMP (Internet Control Message Protocol) is used for diagnostic and error reporting (e.g. ping and traceroute) at the network layer.",
     "networking"),
    ("What is a port number?",
     "A port number (0-65535) identifies a specific process or service on a host. Well-known ports: HTTP=80, HTTPS=443, SSH=22, DNS=53.",
     "networking"),
    ("What is bandwidth?",
     "Bandwidth is the maximum rate of data transfer across a network path, measured in bits per second (bps, Mbps, Gbps).",
     "networking"),
    ("What is latency?",
     "Latency is the time delay for data to travel from source to destination, measured in milliseconds. Lower latency means faster response.",
     "networking"),
    ("What is packet loss?",
     "Packet loss occurs when data packets fail to reach their destination, causing retransmissions (TCP) or gaps (UDP). Common causes: congestion, faulty hardware.",
     "networking"),

    # ── INTERNET ──────────────────────────────────────────────────────
    ("What is the internet?",
     "The internet is a global network of interconnected networks using the TCP/IP protocol suite, enabling communication and data exchange worldwide.",
     "internet"),
    ("What is HTTP?",
     "HTTP (HyperText Transfer Protocol) is an application-layer protocol for transferring web pages and resources between clients (browsers) and servers.",
     "internet"),
    ("What is HTTPS?",
     "HTTPS is HTTP over TLS/SSL, encrypting data in transit to protect confidentiality and integrity between browser and server.",
     "internet"),
    ("What is a URL?",
     "A URL (Uniform Resource Locator) is the address of a resource on the web, consisting of scheme (https), host (example.com), path (/page), and optional query/fragment.",
     "internet"),
    ("What is a web browser?",
     "A web browser is client software (Chrome, Firefox, Safari) that requests, renders, and displays web pages using HTTP/HTTPS.",
     "internet"),
    ("What is a web server?",
     "A web server is software (Apache, Nginx) that listens for HTTP requests and serves web pages, APIs, or files to clients.",
     "internet"),
    ("What is an API?",
     "An API (Application Programming Interface) defines how software components interact. Web APIs use HTTP to exchange data, often in JSON format.",
     "internet"),
    ("What is REST?",
     "REST (Representational State Transfer) is an architectural style for web APIs using standard HTTP methods (GET, POST, PUT, DELETE) on resources identified by URLs.",
     "internet"),
    ("What is a domain name?",
     "A domain name is a human-readable address (like github.com) that maps to an IP address via DNS, organized in a hierarchy (TLD, second-level, subdomain).",
     "internet"),
    ("What is cloud computing?",
     "Cloud computing delivers computing resources (servers, storage, databases) over the internet on-demand, with pay-as-you-go pricing. Major providers: AWS, Azure, GCP.",
     "internet"),
    ("What is a CDN?",
     "A CDN (Content Delivery Network) distributes content across geographically dispersed servers to reduce latency and improve load times for users worldwide.",
     "internet"),
    ("What is FTP?",
     "FTP (File Transfer Protocol) is used to transfer files between client and server over TCP, typically on port 21. SFTP adds SSH encryption.",
     "internet"),
    ("What is SSH?",
     "SSH (Secure Shell) is a protocol for secure remote login and command execution over an encrypted channel, typically on port 22.",
     "internet"),
    ("What is TLS?",
     "TLS (Transport Layer Security) is a cryptographic protocol that provides encryption, authentication, and integrity for data in transit. It replaced SSL.",
     "internet"),
    ("What is a cookie?",
     "An HTTP cookie is a small piece of data stored by the browser, sent with requests to maintain session state, preferences, or tracking information.",
     "internet"),
    ("What is WebSocket?",
     "WebSocket is a protocol providing full-duplex communication over a single TCP connection, enabling real-time data transfer between client and server.",
     "internet"),

    # ── INTRANET ──────────────────────────────────────────────────────
    ("What is an intranet?",
     "An intranet is a private network within an organization that uses internet technologies (TCP/IP, HTTP) for internal communication, collaboration, and resource sharing.",
     "intranet"),
    ("What is the difference between internet and intranet?",
     "The internet is a public global network; an intranet is a private organizational network. Intranets restrict access to authorized users and are typically behind firewalls.",
     "intranet"),
    ("What is an extranet?",
     "An extranet extends an intranet to authorized external users (partners, suppliers) via secure access, often using VPNs or authenticated portals.",
     "intranet"),
    ("What is a VPN?",
     "A VPN (Virtual Private Network) creates an encrypted tunnel over a public network, allowing remote users to securely access an intranet as if they were on the local network.",
     "intranet"),
    ("What is Active Directory?",
     "Active Directory (AD) is Microsoft's directory service for managing users, computers, and resources on a Windows network, providing authentication and authorization.",
     "intranet"),
    ("What is LDAP?",
     "LDAP (Lightweight Directory Access Protocol) is used to query and modify directory services like Active Directory, organizing entries in a hierarchical tree.",
     "intranet"),
    ("What is Single Sign-On?",
     "SSO (Single Sign-On) allows users to authenticate once and access multiple applications without re-entering credentials, using protocols like SAML or OAuth.",
     "intranet"),
    ("What is a proxy server?",
     "A proxy server acts as an intermediary between clients and the internet, providing caching, filtering, and anonymity. Reverse proxies sit in front of servers.",
     "intranet"),
    ("What is network segmentation?",
     "Network segmentation divides a network into isolated sub-networks (segments) to improve security, performance, and management using VLANs, subnets, or firewalls.",
     "intranet"),
    ("What is a DMZ in networking?",
     "A DMZ (Demilitarized Zone) is a perimeter network segment between the internal network and the internet, hosting public-facing services while protecting internal resources.",
     "intranet"),

    # ── SECURITY ──────────────────────────────────────────────────────
    ("What is encryption?",
     "Encryption converts plaintext into ciphertext using an algorithm and key, making data unreadable without the decryption key. Types: symmetric (AES) and asymmetric (RSA).",
     "security"),
    ("What is a DDoS attack?",
     "A DDoS (Distributed Denial of Service) attack overwhelms a target with traffic from many sources, making services unavailable to legitimate users.",
     "security"),
    ("What is phishing?",
     "Phishing is a social engineering attack that uses fake emails or websites to trick users into revealing credentials, financial info, or installing malware.",
     "security"),
    ("What is malware?",
     "Malware is malicious software designed to damage or exploit systems. Types include viruses, worms, trojans, ransomware, spyware, and adware.",
     "security"),
    ("What is a zero-day vulnerability?",
     "A zero-day vulnerability is a software flaw unknown to the vendor with no available patch, exploitable by attackers before a fix is released.",
     "security"),
    ("What is two-factor authentication?",
     "2FA requires two forms of identity verification: something you know (password) and something you have (phone/token) or are (biometrics), adding a security layer.",
     "security"),
    ("What is an SSL certificate?",
     "An SSL/TLS certificate authenticates a website's identity and enables encrypted connections. Issued by Certificate Authorities (CAs), it contains the public key.",
     "security"),
    ("What is a man-in-the-middle attack?",
     "A MITM attack intercepts communication between two parties, allowing the attacker to eavesdrop or alter data. HTTPS and certificate pinning help prevent this.",
     "security"),
    ("What is SQL injection?",
     "SQL injection is an attack where malicious SQL code is inserted into input fields to manipulate a database. Prevention: parameterized queries and input validation.",
     "security"),
    ("What is XSS?",
     "XSS (Cross-Site Scripting) injects malicious scripts into web pages viewed by others. Prevention: output encoding, Content Security Policy, input sanitization.",
     "security"),

    # ── PROTOCOLS & STANDARDS ─────────────────────────────────────────
    ("What is IPv4?",
     "IPv4 is the fourth version of the Internet Protocol using 32-bit addresses (4.3 billion possible). Addresses look like 192.168.0.1. Limited address space led to IPv6.",
     "networking"),
    ("What is IPv6?",
     "IPv6 uses 128-bit addresses (virtually unlimited), written in hex like 2001:0db8::1. It provides built-in IPsec, simplified headers, and no need for NAT.",
     "networking"),
    ("What is BGP?",
     "BGP (Border Gateway Protocol) is the routing protocol that manages how packets are routed across the internet between autonomous systems (AS).",
     "networking"),
    ("What is OSPF?",
     "OSPF (Open Shortest Path First) is a link-state interior gateway protocol that uses Dijkstra's algorithm to find the shortest path within an autonomous system.",
     "networking"),
    ("What is SMTP?",
     "SMTP (Simple Mail Transfer Protocol) is used to send emails between servers on port 25/587. It handles outgoing mail; POP3/IMAP handle retrieval.",
     "internet"),
    ("What is IMAP?",
     "IMAP (Internet Message Access Protocol) retrieves email from a server while keeping messages stored server-side, allowing multi-device access.",
     "internet"),

    # ── WI-FI FUNDAMENTALS ────────────────────────────────────────────
    ("What is Wi-Fi?",
     "Wi-Fi is a wireless networking technology based on the IEEE 802.11 standards that allows devices to connect to a LAN without physical cables, using radio frequencies in the 2.4 GHz and 5 GHz bands.",
     "wifi"),
    ("What is 802.11?",
     "IEEE 802.11 is the family of standards for wireless LANs. Key versions: 802.11a (5 GHz, 54 Mbps), 802.11b (2.4 GHz, 11 Mbps), 802.11g (2.4 GHz, 54 Mbps), 802.11n/Wi-Fi 4 (up to 600 Mbps), 802.11ac/Wi-Fi 5 (up to 3.5 Gbps), 802.11ax/Wi-Fi 6 (up to 9.6 Gbps).",
     "wifi"),
    ("What is the difference between 2.4 GHz and 5 GHz Wi-Fi?",
     "2.4 GHz has longer range and better wall penetration but more interference and lower speeds (up to ~600 Mbps). 5 GHz offers faster speeds (up to 3.5+ Gbps) and less interference but shorter range. Wi-Fi 6E adds 6 GHz.",
     "wifi"),
    ("What is Wi-Fi 6?",
     "Wi-Fi 6 (802.11ax) supports speeds up to 9.6 Gbps, uses OFDMA and MU-MIMO for better multi-device performance, includes Target Wake Time (TWT) for power savings, and uses WPA3 security by default.",
     "wifi"),
    ("What is Wi-Fi 6E?",
     "Wi-Fi 6E extends Wi-Fi 6 into the 6 GHz band, adding up to 1200 MHz of new spectrum with 7 additional 160 MHz channels, reducing congestion and enabling faster speeds with less interference.",
     "wifi"),
    ("What is an SSID?",
     "An SSID (Service Set Identifier) is the name of a wireless network that clients see when scanning. It can be up to 32 characters. Enterprise networks often use multiple SSIDs for different security zones (e.g., Corporate, Guest, IoT).",
     "wifi"),
    ("What is a wireless access point?",
     "A wireless access point (WAP/AP) is a device that bridges wireless clients to a wired network. Enterprise APs support multiple SSIDs, VLANs, PoE, and centralized management via a wireless controller.",
     "wifi"),
    ("What is a wireless controller?",
     "A wireless LAN controller (WLC) centrally manages multiple access points, handling configuration, firmware updates, roaming, load balancing, and security policies. Examples: Cisco WLC, Aruba Mobility Controller.",
     "wifi"),
    ("What is OFDMA?",
     "OFDMA (Orthogonal Frequency-Division Multiple Access) is a Wi-Fi 6 technology that divides a channel into smaller sub-channels (Resource Units), allowing an AP to transmit to multiple devices simultaneously, reducing latency.",
     "wifi"),
    ("What is MU-MIMO?",
     "MU-MIMO (Multi-User, Multiple-Input, Multiple-Output) allows an access point to communicate with multiple devices at the same time using multiple antennas. Wi-Fi 5 supports downlink MU-MIMO; Wi-Fi 6 adds uplink MU-MIMO.",
     "wifi"),
    ("What is beamforming?",
     "Beamforming is a Wi-Fi signal-focusing technique where the AP directs radio signals toward specific clients rather than broadcasting in all directions, improving signal strength, range, and throughput.",
     "wifi"),
    ("What is a Wi-Fi channel?",
     "Wi-Fi channels are sub-divisions of the frequency band. 2.4 GHz has 14 channels (1, 6, 11 are non-overlapping). 5 GHz has 25+ non-overlapping channels. Proper channel planning avoids co-channel interference.",
     "wifi"),
    ("What is channel bonding?",
     "Channel bonding combines adjacent Wi-Fi channels to increase bandwidth. 802.11n bonds 2×20 MHz = 40 MHz; 802.11ac supports 80 and 160 MHz; 802.11ax supports 160 MHz in 5/6 GHz bands.",
     "wifi"),
    ("What is DFS in Wi-Fi?",
     "DFS (Dynamic Frequency Selection) allows Wi-Fi to use 5 GHz channels shared with weather radar. APs must detect radar signals and vacate the channel within seconds, providing more available spectrum but requiring radar avoidance.",
     "wifi"),
    ("What is a mesh Wi-Fi network?",
     "A mesh Wi-Fi network uses multiple interconnected nodes (APs) that self-organize to provide seamless coverage. Nodes communicate via a wireless backhaul, and clients roam transparently. Enterprise examples: Cisco Meraki, Aruba Instant On.",
     "wifi"),
    ("What is Wi-Fi roaming?",
     "Wi-Fi roaming is when a client moves between access points without losing connectivity. Fast roaming protocols (802.11r/FT, 802.11k, 802.11v) reduce handoff time to under 50 ms for seamless voice/video.",
     "wifi"),
    ("What is 802.11r?",
     "802.11r (Fast BSS Transition/FT) pre-authenticates clients with neighboring APs, reducing roaming handoff from hundreds of milliseconds to under 50 ms — critical for VoIP and real-time applications.",
     "wifi"),
    ("What is band steering?",
     "Band steering encourages dual-band clients to connect to the less-congested 5 GHz band instead of 2.4 GHz by delaying probe responses on 2.4 GHz or using 802.11v BSS Transition Management frames.",
     "wifi"),

    # ── CORPORATE WI-FI SECURITY ──────────────────────────────────────
    ("What is WPA2?",
     "WPA2 (Wi-Fi Protected Access 2) uses AES-CCMP encryption and is the minimum security standard for enterprise Wi-Fi. WPA2-Personal uses a pre-shared key (PSK); WPA2-Enterprise uses 802.1X/RADIUS authentication.",
     "wifi_security"),
    ("What is WPA3?",
     "WPA3 replaces WPA2 with stronger security: SAE (Simultaneous Authentication of Equals) replaces PSK, providing forward secrecy. WPA3-Enterprise adds 192-bit cryptographic strength. It mitigates KRACK and dictionary attacks.",
     "wifi_security"),
    ("What is WPA2-Enterprise?",
     "WPA2-Enterprise uses 802.1X authentication with a RADIUS server. Each user has unique credentials (username/password or certificate). It provides per-user encryption keys, audit trails, and centralized access control — the standard for corporate Wi-Fi.",
     "wifi_security"),
    ("What is WPA3-Enterprise?",
     "WPA3-Enterprise provides 192-bit minimum security using CNSA suite ciphers (AES-256-GCM, SHA-384). It offers stronger key establishment, mandatory Protected Management Frames (PMF), and is required for government/defense networks.",
     "wifi_security"),
    ("What is 802.1X?",
     "802.1X is a port-based network access control standard. It uses three roles: supplicant (client), authenticator (AP/switch), and authentication server (RADIUS). The client must authenticate before gaining network access.",
     "wifi_security"),
    ("What is RADIUS?",
     "RADIUS (Remote Authentication Dial-In User Service) is a protocol for centralized authentication, authorization, and accounting (AAA). In corporate Wi-Fi, the AP forwards credentials to the RADIUS server, which validates them against Active Directory or LDAP.",
     "wifi_security"),
    ("What is EAP?",
     "EAP (Extensible Authentication Protocol) is a framework for authentication used with 802.1X. Common EAP methods: EAP-TLS (certificates), PEAP (password + server cert), EAP-TTLS, EAP-FAST. EAP-TLS is the most secure.",
     "wifi_security"),
    ("What is EAP-TLS?",
     "EAP-TLS uses mutual certificate-based authentication — both the client and RADIUS server present X.509 certificates. It's the gold standard for enterprise Wi-Fi security, eliminating password-based attacks entirely.",
     "wifi_security"),
    ("What is PEAP?",
     "PEAP (Protected EAP) creates an encrypted TLS tunnel to the RADIUS server, then authenticates the user inside it (typically MSCHAPv2). The server needs a certificate but clients use username/password — common in corporate networks with Active Directory.",
     "wifi_security"),
    ("What is a pre-shared key?",
     "A PSK (Pre-Shared Key) is a shared password used in WPA2/WPA3-Personal. All users share the same key, making it unsuitable for enterprises — if one device is compromised, every device's key is exposed. Use 802.1X instead.",
     "wifi_security"),
    ("What is SAE in WPA3?",
     "SAE (Simultaneous Authentication of Equals) is WPA3's replacement for PSK. It uses a Dragonfly key exchange that provides forward secrecy — even if the password is later compromised, past traffic cannot be decrypted.",
     "wifi_security"),
    ("What is a KRACK attack?",
     "KRACK (Key Reinstallation Attack) exploits a flaw in WPA2's four-way handshake by manipulating and replaying cryptographic handshake messages, potentially allowing decryption of traffic. WPA3's SAE and patched WPA2 mitigate it.",
     "wifi_security"),
    ("What is PMF in Wi-Fi?",
     "PMF (Protected Management Frames, 802.11w) encrypts management frames like deauthentication and disassociation, preventing spoofed disconnect attacks. It's mandatory in WPA3 and recommended for all enterprise networks.",
     "wifi_security"),
    ("What is a rogue access point?",
     "A rogue AP is an unauthorized access point connected to the corporate network, potentially bypassing security controls. Wireless IDS/IPS and NAC solutions detect rogues by monitoring for unknown BSSIDs and containing them with deauth frames.",
     "wifi_security"),
    ("What is an evil twin attack?",
     "An evil twin is a malicious AP that mimics a legitimate SSID to trick clients into connecting. The attacker intercepts all traffic. Prevention: 802.1X mutual authentication, certificate validation, and wireless IDS.",
     "wifi_security"),
    ("What is wireless intrusion detection?",
     "A WIDS/WIPS (Wireless Intrusion Detection/Prevention System) monitors the RF environment for rogue APs, evil twins, deauth floods, and policy violations. It can automatically contain threats by sending deauthentication frames.",
     "wifi_security"),
    ("What is MAC filtering?",
     "MAC filtering restricts network access to devices with pre-approved MAC addresses. However, MAC addresses are easily spoofed, so MAC filtering alone is NOT a security control — it's only useful as a minor additional layer alongside 802.1X.",
     "wifi_security"),
    ("What is captive portal authentication?",
     "A captive portal redirects unauthenticated Wi-Fi users to a login web page before granting network access. Used for guest networks, it supports username/password, social login, or terms acceptance. Enterprise examples: Cisco ISE, Aruba ClearPass.",
     "wifi_security"),
    ("What is NAC?",
     "NAC (Network Access Control) enforces security policies before granting network access. It checks device health (OS patches, antivirus), user identity, and compliance before allowing connection. Solutions: Cisco ISE, Aruba ClearPass, FortiNAC.",
     "wifi_security"),
    ("What is wireless security best practice?",
     "Enterprise Wi-Fi security best practices: use WPA3-Enterprise or WPA2-Enterprise with 802.1X/EAP-TLS, enable PMF, segment traffic with VLANs, deploy WIDS/WIPS, disable WPS, use strong RADIUS server certificates, implement NAC, and audit regularly.",
     "wifi_security"),

    # ── CORPORATE WI-FI RESTRICTIONS & POLICIES ───────────────────────
    ("What are corporate Wi-Fi restrictions?",
     "Corporate Wi-Fi restrictions include: content filtering (blocking categories like social media, gambling), bandwidth throttling per user/role, device whitelisting, application control (blocking P2P/VPN tunnels), time-based access, and guest isolation.",
     "wifi_policy"),
    ("How do companies restrict Wi-Fi access?",
     "Companies restrict Wi-Fi via: 802.1X identity-based access (employees vs guests vs contractors), Group Policy and RADIUS attributes that assign users to specific VLANs, URL/content filtering through proxy or DNS, firewall ACLs, and bandwidth quotas.",
     "wifi_policy"),
    ("What is a guest Wi-Fi network?",
     "A guest Wi-Fi network is an isolated SSID for visitors that provides internet access but blocks access to internal corporate resources. It uses a separate VLAN, captive portal authentication, bandwidth limits, and client isolation to prevent lateral movement.",
     "wifi_policy"),
    ("What is client isolation on Wi-Fi?",
     "Client isolation (also called AP isolation or peer-to-peer blocking) prevents wireless clients on the same SSID from communicating with each other. Essential on guest networks to stop lateral attacks between untrusted devices.",
     "wifi_policy"),
    ("What is bandwidth throttling on Wi-Fi?",
     "Bandwidth throttling limits per-user or per-device throughput on the wireless network. Implemented via QoS policies on the controller or AP, it prevents any single user from monopolizing bandwidth. Typical limits: 10-50 Mbps for guests, higher for employees.",
     "wifi_policy"),
    ("What is content filtering on corporate Wi-Fi?",
     "Content filtering blocks or restricts access to specific website categories (gambling, adult, malware, social media) on the corporate network. Implemented via DNS filtering (Cisco Umbrella, Zscaler), web proxy, or next-gen firewall URL categorization.",
     "wifi_policy"),
    ("What is application control on Wi-Fi?",
     "Application control uses deep packet inspection (DPI) to identify and manage specific applications on the wireless network — blocking P2P file sharing, throttling video streaming, or prioritizing business apps like Microsoft 365, Zoom, and Salesforce.",
     "wifi_policy"),
    ("What is DNS filtering?",
     "DNS filtering blocks malicious or policy-violating domains at the DNS resolution level. When a device queries a blocked domain, the DNS returns a block page instead. Solutions: Cisco Umbrella, Cloudflare Gateway, Zscaler. Faster than proxy-based filtering.",
     "wifi_policy"),
    ("What is QoS on Wi-Fi?",
     "QoS (Quality of Service) prioritizes network traffic by type. WMM (Wi-Fi Multimedia) defines four access categories: Voice (highest), Video, Best Effort, Background (lowest). Corporate networks prioritize VoIP and video over bulk downloads.",
     "wifi_policy"),
    ("What is WMM?",
     "WMM (Wi-Fi Multimedia) is a QoS standard based on 802.11e that prioritizes time-sensitive traffic. It defines four categories: Voice (AC_VO), Video (AC_VI), Best Effort (AC_BE), and Background (AC_BK). Required for Wi-Fi certification.",
     "wifi_policy"),
    ("What is a Wi-Fi acceptable use policy?",
     "A Wi-Fi acceptable use policy (AUP) defines permitted and prohibited activities on the corporate wireless network: no unauthorized APs, no sharing credentials, personal devices must comply with BYOD policy, company may monitor traffic, violations may result in termination.",
     "wifi_policy"),
    ("What is BYOD Wi-Fi policy?",
     "BYOD (Bring Your Own Device) Wi-Fi policy governs personal devices on corporate networks. Typically requires: MDM enrollment, OS security patches, antivirus, device certificate provisioning, and placement on a restricted VLAN with limited access to internal resources.",
     "wifi_policy"),
    ("What is MDM for Wi-Fi?",
     "MDM (Mobile Device Management) enforces security policies on devices connecting to corporate Wi-Fi: enforcing screen locks, encryption, OS updates, certificate deployment, remote wipe capability, and blocking jailbroken/rooted devices. Examples: Intune, Jamf, VMware Workspace ONE.",
     "wifi_policy"),
    ("What is network access based on user role?",
     "Role-based access control (RBAC) on Wi-Fi assigns network permissions based on the user's role via RADIUS attributes. Executives get full access; interns get restricted access; guests get internet-only. Implemented through dynamic VLAN assignment and downloadable ACLs.",
     "wifi_policy"),
    ("What is a downloadable ACL?",
     "A downloadable ACL (dACL) is an access control list pushed from the RADIUS/NAC server to the switch or AP after authentication. It dynamically restricts what resources each user can access based on their identity and role — central to zero-trust wireless.",
     "wifi_policy"),
    ("What is dynamic VLAN assignment?",
     "Dynamic VLAN assignment places authenticated users into specific VLANs based on RADIUS attributes (Tunnel-Type, Tunnel-Medium-Type, Tunnel-Private-Group-ID). An employee goes to VLAN 10, a contractor to VLAN 20, a guest to VLAN 100.",
     "wifi_policy"),

    # ── ENTERPRISE NETWORK PROTOCOLS ──────────────────────────────────
    ("What is STP?",
     "STP (Spanning Tree Protocol, 802.1D) prevents Layer 2 loops in switched networks by logically blocking redundant paths. RSTP (802.1w) converges faster. MSTP (802.1s) supports multiple instances for VLAN groups.",
     "networking"),
    ("What is LACP?",
     "LACP (Link Aggregation Control Protocol, 802.3ad) bundles multiple physical links into a single logical link (EtherChannel/port-channel), increasing bandwidth and providing redundancy between switches or switch-to-server.",
     "networking"),
    ("What is 802.1Q?",
     "802.1Q is the VLAN tagging standard. It inserts a 4-byte tag into Ethernet frames containing the VLAN ID (1-4094), allowing switches to carry multiple VLANs over a single trunk link.",
     "networking"),
    ("What is a trunk port?",
     "A trunk port carries traffic for multiple VLANs over a single link using 802.1Q tags. The native VLAN's frames are sent untagged. Mismatched native VLANs between switches cause VLAN hopping vulnerabilities.",
     "networking"),
    ("What is SNMP?",
     "SNMP (Simple Network Management Protocol) monitors and manages network devices. SNMPv1/v2c use community strings (insecure). SNMPv3 adds authentication and encryption. Used with NMS tools like SolarWinds, PRTG, Nagios.",
     "networking"),
    ("What is NetFlow?",
     "NetFlow (Cisco) exports IP traffic flow data from routers/switches for analysis. Each flow is defined by src/dst IP, ports, protocol. Used for bandwidth monitoring, traffic analysis, and anomaly detection. Standards: IPFIX, sFlow.",
     "networking"),
    ("What is MPLS?",
     "MPLS (Multiprotocol Label Switching) routes traffic using short labels instead of long IP lookups, enabling traffic engineering, VPNs (L3VPN, L2VPN), and QoS. Being replaced by SD-WAN in many enterprise WANs.",
     "networking"),
    ("What is SD-WAN?",
     "SD-WAN (Software-Defined WAN) uses software to manage WAN connections (MPLS, broadband, LTE), providing intelligent path selection, encryption, and centralized policy management. Vendors: Cisco Viptela, VMware VeloCloud, Fortinet, Silver Peak.",
     "networking"),
    ("What is PoE?",
     "PoE (Power over Ethernet, 802.3af/at/bt) delivers electrical power along with data over Ethernet cables. 802.3af provides 15.4W; 802.3at (PoE+) 30W; 802.3bt (PoE++) up to 90W. Used for APs, IP cameras, VoIP phones.",
     "networking"),
    ("What is EIGRP?",
     "EIGRP (Enhanced Interior Gateway Routing Protocol) is Cisco's advanced distance-vector routing protocol. It uses DUAL algorithm for fast convergence, supports unequal-cost load balancing, and is now an open standard (RFC 7868).",
     "networking"),
    ("What is RIP?",
     "RIP (Routing Information Protocol) is a distance-vector protocol using hop count (max 15). RIPv2 adds CIDR and authentication. Simple but slow convergence — replaced by OSPF/EIGRP in enterprise networks.",
     "networking"),
    ("What is HSRP?",
     "HSRP (Hot Standby Router Protocol, Cisco) provides gateway redundancy. Two or more routers share a virtual IP; the active router handles traffic while standbys monitor and take over if it fails. Standards-based alternative: VRRP.",
     "networking"),
    ("What is VRRP?",
     "VRRP (Virtual Router Redundancy Protocol) is an open standard for gateway redundancy. Multiple routers share a virtual IP address; the master forwards traffic and backups automatically take over on failure.",
     "networking"),

    # ── ENTERPRISE SECURITY (DEEP) ────────────────────────────────────
    ("What is IPsec?",
     "IPsec is a protocol suite that encrypts and authenticates IP packets. It operates in Transport mode (end-to-end) or Tunnel mode (site-to-site VPN). Uses AH for authentication and ESP for encryption+authentication. IKEv2 handles key exchange.",
     "security"),
    ("What is IKEv2?",
     "IKEv2 (Internet Key Exchange version 2) negotiates IPsec security associations. It provides fast reconnection (MOBIKE for mobile), NAT traversal, built-in DoS protection, and is the preferred VPN key exchange protocol.",
     "security"),
    ("What is a site-to-site VPN?",
     "A site-to-site VPN creates a permanent encrypted IPsec tunnel between two networks (e.g., headquarters and branch office). Traffic is encrypted at the gateway router/firewall transparently to end users.",
     "security"),
    ("What is SSL VPN?",
     "An SSL/TLS VPN provides remote access through a web browser or lightweight client using HTTPS (port 443). Types: clientless (web portal) and full-tunnel (routes all traffic). Examples: Cisco AnyConnect, Palo Alto GlobalProtect.",
     "security"),
    ("What is a next-generation firewall?",
     "An NGFW combines traditional firewall with application awareness (DPI), IPS, URL filtering, malware sandboxing, SSL inspection, and user identity integration. Vendors: Palo Alto, Fortinet FortiGate, Cisco Firepower, Check Point.",
     "security"),
    ("What is IDS vs IPS?",
     "IDS (Intrusion Detection System) monitors and alerts on suspicious traffic. IPS (Intrusion Prevention System) also blocks threats inline. Both use signature-based and anomaly-based detection. IPS is active; IDS is passive.",
     "security"),
    ("What is SIEM?",
     "SIEM (Security Information and Event Management) collects, correlates, and analyzes logs from network devices, servers, and applications to detect security threats. Examples: Splunk, Microsoft Sentinel, IBM QRadar, Elastic SIEM.",
     "security"),
    ("What is zero trust security?",
     "Zero trust assumes no user, device, or network is trusted by default. Every access request is verified: identity + device health + context. Principles: least privilege, microsegmentation, continuous verification. 'Never trust, always verify.'",
     "security"),
    ("What is microsegmentation?",
     "Microsegmentation creates fine-grained security zones within a network, applying policies to individual workloads rather than subnets. It limits lateral movement after a breach. Implemented via SDN, host-based firewalls, or NSX.",
     "security"),
    ("What is endpoint detection and response?",
     "EDR monitors endpoints for suspicious behavior (process injection, lateral movement, credential theft), provides real-time alerting, forensic data collection, and automated response. Examples: CrowdStrike Falcon, Microsoft Defender for Endpoint, SentinelOne.",
     "security"),
    ("What is a certificate authority?",
     "A CA (Certificate Authority) issues digital certificates that bind a public key to an identity. Enterprise CAs (Microsoft AD CS) issue certificates for 802.1X, VPN, web servers. Public CAs include DigiCert, Let's Encrypt, Sectigo.",
     "security"),
    ("What is PKI?",
     "PKI (Public Key Infrastructure) is the framework for creating, distributing, and revoking digital certificates. Components: CA, Registration Authority, Certificate Revocation List (CRL), OCSP responder. Essential for enterprise 802.1X and VPN.",
     "security"),
    ("What is ransomware?",
     "Ransomware encrypts a victim's files and demands payment for the decryption key. Prevention: offline backups, patch management, EDR, email filtering, network segmentation, user training. Never pay — it funds criminal operations.",
     "security"),
    ("What is social engineering?",
     "Social engineering manipulates people into revealing confidential information or performing actions. Types: phishing, vishing (phone), smishing (SMS), pretexting, tailgating, baiting. Defense: security awareness training and verification procedures.",
     "security"),
    ("What is penetration testing?",
     "Penetration testing simulates real attacks against systems to find vulnerabilities before attackers do. Types: black box (no knowledge), white box (full access), gray box (partial). Frameworks: OWASP, PTES, NIST SP 800-115.",
     "security"),
    ("What is NIST cybersecurity framework?",
     "The NIST CSF provides guidelines for managing cybersecurity risk: Identify (assets/risks), Protect (safeguards), Detect (monitoring), Respond (incident handling), Recover (restoration). Widely adopted by enterprises and required for US government contractors.",
     "security"),

    # ── NETWORK TROUBLESHOOTING ───────────────────────────────────────
    ("How to troubleshoot slow Wi-Fi?",
     "Slow Wi-Fi troubleshooting: 1) Check channel utilization and interference (Wi-Fi analyzer), 2) Verify client is on 5 GHz not 2.4 GHz, 3) Check AP client count (overloaded?), 4) Test wired speed (is it the WAN?), 5) Check for rogue APs, 6) Update AP firmware, 7) Verify QoS/bandwidth policies.",
     "troubleshooting"),
    ("How to troubleshoot Wi-Fi disconnections?",
     "Wi-Fi disconnect troubleshooting: 1) Check RSSI (-67 dBm minimum for reliable), 2) Verify roaming settings (802.11r/k/v enabled?), 3) Check for channel changes (DFS radar?), 4) Review AP logs for deauth reasons, 5) Check DHCP lease times, 6) Test with different client for driver issues.",
     "troubleshooting"),
    ("What is RSSI?",
     "RSSI (Received Signal Strength Indicator) measures Wi-Fi signal power. Good: -30 to -67 dBm; Usable: -67 to -70 dBm; Weak: -70 to -80 dBm; Unusable: below -80 dBm. For VoIP, -67 dBm minimum is required.",
     "troubleshooting"),
    ("What is SNR in Wi-Fi?",
     "SNR (Signal-to-Noise Ratio) is the difference between signal strength and noise floor. Above 40 dB: excellent; 25-40 dB: good; 15-25 dB: marginal; below 15 dB: unusable. More important than RSSI alone for connection quality.",
     "troubleshooting"),
    ("How to do a Wi-Fi site survey?",
     "A Wi-Fi site survey maps signal coverage, interference, and performance. Tools: Ekahau, NetSpot, AirMagnet. Steps: 1) Create floor plan, 2) Walk the space measuring signal, 3) Identify dead zones, 4) Plan AP placement for -67 dBm coverage with 15-20% overlap, 5) Validate with active testing.",
     "troubleshooting"),
    ("How to troubleshoot DNS issues?",
     "DNS troubleshooting: 1) nslookup/dig to test resolution, 2) Check if specific DNS server fails (nslookup domain server), 3) Flush DNS cache (ipconfig /flushdns or resolvectl flush-caches), 4) Check /etc/resolv.conf or DHCP-assigned DNS, 5) Test with public DNS (8.8.8.8, 1.1.1.1).",
     "troubleshooting"),
    ("How to troubleshoot DHCP issues?",
     "DHCP troubleshooting: 1) ipconfig /release then /renew, 2) Check DHCP server scope (enough addresses?), 3) Verify DHCP relay/ip helper on router, 4) Check DHCP lease table for conflicts, 5) Look for rogue DHCP servers, 6) Verify VLAN tagging on trunk to DHCP server.",
     "troubleshooting"),
    ("How to troubleshoot VPN connectivity?",
     "VPN troubleshooting: 1) Verify internet connectivity first, 2) Check VPN server address and port (443/500/4500), 3) Test with different network (is the ISP blocking?), 4) Review client logs for certificate/authentication errors, 5) Check split vs full tunnel config, 6) Verify firewall allows IPsec/IKE.",
     "troubleshooting"),
    ("What is traceroute?",
     "Traceroute (tracert on Windows) shows the path packets take to a destination by sending packets with incrementing TTL values. Each hop responds with ICMP Time Exceeded. Useful for finding where latency or packet loss occurs in the network path.",
     "troubleshooting"),
    ("What is Wireshark?",
     "Wireshark is a network protocol analyzer (packet sniffer) that captures and inspects network traffic in real-time. Used for troubleshooting, security analysis, and protocol debugging. Can decode 2000+ protocols. Capture filters use BPF syntax.",
     "troubleshooting"),
    ("How to troubleshoot 802.1X authentication failures?",
     "802.1X troubleshooting: 1) Check RADIUS server reachability and shared secret, 2) Verify server certificate is trusted by client, 3) Check EAP method matches on both sides, 4) Review RADIUS server logs for reject reason, 5) Test with known-good account, 6) Check NTP sync (certificate time validation).",
     "troubleshooting"),
    ("How to troubleshoot network latency?",
     "Latency troubleshooting: 1) ping to measure RTT, 2) traceroute to find slow hop, 3) Check bandwidth utilization (NetFlow/SNMP), 4) Look for duplex mismatches, 5) Check for packet loss (extended ping), 6) Verify QoS policies, 7) Test DNS resolution time, 8) Check for asymmetric routing.",
     "troubleshooting"),

    # ── GROUP POLICY & WINDOWS NETWORKING ─────────────────────────────
    ("What is Group Policy?",
     "Group Policy (GPO) is a Windows feature that allows centralized management of user and computer settings across an Active Directory domain. Admins configure policies for Wi-Fi profiles, firewall rules, software deployment, screen locks, and security settings.",
     "intranet"),
    ("How does Group Policy deploy Wi-Fi profiles?",
     "Group Policy can push Wi-Fi profiles to domain-joined computers via Computer Configuration → Policies → Windows Settings → Security Settings → Wireless Network Policies. This auto-configures SSID, security (WPA2-Enterprise), EAP type, and trusted certificates.",
     "intranet"),
    ("What is NPS?",
     "NPS (Network Policy Server) is Microsoft's RADIUS server for Windows. It authenticates 802.1X wireless/wired clients against Active Directory, supports EAP-TLS and PEAP, and assigns VLAN/ACL via RADIUS attributes based on AD group membership.",
     "intranet"),
    ("What is Kerberos?",
     "Kerberos is an authentication protocol used by Active Directory. It uses tickets (TGT, service tickets) issued by the Key Distribution Center (KDC) to authenticate users without sending passwords over the network. Default auth for Windows domains.",
     "intranet"),
    ("What is NTLM?",
     "NTLM (NT LAN Manager) is a legacy Windows authentication protocol using challenge-response. It's weaker than Kerberos — vulnerable to pass-the-hash and relay attacks. Should be disabled in favor of Kerberos where possible.",
     "intranet"),
    ("What is DNS in Active Directory?",
     "Active Directory requires DNS for domain controller location (SRV records), client domain join, and replication. AD-integrated DNS zones store records in AD and replicate with DC replication. Proper DNS is critical — AD fails without it.",
     "intranet"),

    # ── ADVANCED PROTOCOLS & CONCEPTS ─────────────────────────────────
    ("What is ARP spoofing?",
     "ARP spoofing sends fake ARP replies to associate the attacker's MAC with a victim's IP, enabling MITM attacks on the LAN. Prevention: Dynamic ARP Inspection (DAI), static ARP entries, and 802.1X port security.",
     "security"),
    ("What is DHCP snooping?",
     "DHCP snooping is a Layer 2 security feature that filters untrusted DHCP messages. It allows DHCP responses only from trusted ports (where the DHCP server is), preventing rogue DHCP attacks. Builds a binding table used by DAI and IP Source Guard.",
     "security"),
    ("What is port security?",
     "Port security limits the number of MAC addresses on a switch port and can restrict to specific MACs. Violations trigger shutdown, restrict, or protect mode. Helps prevent MAC flooding and unauthorized device connection.",
     "security"),
    ("What is 802.1X wired authentication?",
     "802.1X works on wired ports too — the switch acts as authenticator, blocking traffic until the client authenticates via RADIUS. Used to prevent unauthorized devices from plugging into corporate Ethernet jacks. Often combined with MAB for non-802.1X devices.",
     "security"),
    ("What is MAB?",
     "MAB (MAC Authentication Bypass) authenticates devices that can't do 802.1X (printers, IP phones, IoT) by sending their MAC address to RADIUS as the username/password. Less secure than 802.1X but necessary for legacy devices. Always profile these devices.",
     "security"),
    ("What is TACACS+?",
     "TACACS+ (Terminal Access Controller Access-Control System Plus) is a Cisco protocol for device administration AAA. Unlike RADIUS, it separates authentication, authorization, and accounting, and encrypts the entire packet body. Used for switch/router admin access.",
     "security"),
    ("What is a honey pot?",
     "A honeypot is a decoy system designed to attract attackers and study their methods. Network honeypots detect unauthorized scanning; Wi-Fi honeypots detect rogue AP attackers. They provide early warning without risking real assets.",
     "security"),
    ("What is DLP?",
     "DLP (Data Loss Prevention) monitors and prevents sensitive data (PII, financial, IP) from leaving the network. It inspects email, web uploads, USB transfers, and cloud storage. Solutions: Symantec DLP, Microsoft Purview, Forcepoint.",
     "security"),

    # ── CLOUD & MODERN NETWORKING ─────────────────────────────────────
    ("What is SASE?",
     "SASE (Secure Access Service Edge) combines SD-WAN with cloud-delivered security (SWG, CASB, ZTNA, FWaaS) into a single service. It secures users regardless of location. Vendors: Zscaler, Palo Alto Prisma, Netskope, Cisco.",
     "networking"),
    ("What is ZTNA?",
     "ZTNA (Zero Trust Network Access) replaces traditional VPN by providing per-application access based on identity and context. Users only see apps they're authorized for — no network-level access. Part of SASE architectures.",
     "security"),
    ("What is CASB?",
     "A CASB (Cloud Access Security Broker) sits between users and cloud services, enforcing security policies: visibility into shadow IT, DLP for cloud data, threat protection, and compliance monitoring. Examples: Netskope, Microsoft Defender for Cloud Apps.",
     "security"),
    ("What is SWG?",
     "A SWG (Secure Web Gateway) filters web traffic to enforce acceptable use policies, block malware, and prevent data leakage. Cloud-based SWGs protect remote users without backhauling traffic to the corporate network.",
     "security"),
    ("What is SDN?",
     "SDN (Software-Defined Networking) separates the control plane from the data plane, centralizing network management via a controller. It enables programmable, automated network configuration. Protocols: OpenFlow. Products: Cisco ACI, VMware NSX.",
     "networking"),
    ("What is network automation?",
     "Network automation uses scripts and tools to configure, manage, and operate network devices without manual CLI. Tools: Ansible, Python (Netmiko, NAPALM), Terraform. Protocols: NETCONF/YANG, REST APIs, gNMI.",
     "networking"),

    # ── WIRELESS SITE DESIGN & PLANNING ───────────────────────────────
    ("How many users can one AP handle?",
     "A typical enterprise AP handles 30-50 active clients comfortably. High-density APs (Wi-Fi 6) can manage 100+ with OFDMA. For lecture halls or stadiums, plan for 1 AP per 25-30 users max. Always validate with a site survey.",
     "wifi"),
    ("What is AP-on-a-stick?",
     "AP-on-a-stick is a survey technique where an AP is mounted on an adjustable pole at the planned installation height. The surveyor walks the floor measuring signal to validate coverage before permanent installation.",
     "wifi"),
    ("What is a heat map in Wi-Fi?",
     "A Wi-Fi heat map is a visual representation of signal strength overlaid on a floor plan. Colors indicate signal levels (green=strong, red=weak). Generated by site survey tools like Ekahau or NetSpot to identify dead zones and AP placement.",
     "wifi"),
    ("How to plan enterprise Wi-Fi for a building?",
     "Enterprise Wi-Fi planning: 1) Define requirements (users, devices, apps), 2) Get floor plans, 3) Conduct predictive survey (Ekahau), 4) Place APs for -67 dBm coverage with 15-20% cell overlap, 5) Assign channels (1/6/11 on 2.4 GHz, plan 5 GHz), 6) Configure VLANs and security, 7) Validate with post-deployment survey.",
     "wifi"),
    ("What is co-channel interference?",
     "Co-channel interference (CCI) occurs when neighboring APs use the same channel, forcing them to share airtime. It reduces throughput but doesn't corrupt signals. Mitigation: proper channel planning, transmit power reduction, 5 GHz preference.",
     "wifi"),
    ("What is adjacent channel interference?",
     "Adjacent channel interference (ACI) occurs when nearby APs use overlapping channels (e.g., channels 1 and 3 on 2.4 GHz). It causes real signal corruption. Prevention: use only non-overlapping channels (1, 6, 11 on 2.4 GHz).",
     "wifi"),

    # ── IoT & SPECIALIZED NETWORKING ──────────────────────────────────
    ("How should IoT devices connect to corporate Wi-Fi?",
     "IoT devices should be on a dedicated SSID mapped to an isolated VLAN with strict firewall ACLs. Use MAB or PSK-based auth (not on the corporate SSID). Apply microsegmentation to limit IoT lateral movement. Monitor for anomalous traffic patterns.",
     "wifi_security"),
    ("What is 802.11ah?",
     "802.11ah (Wi-Fi HaLow) operates in the 900 MHz band, designed for IoT with long range (1 km+), low power, and modest throughput. Penetrates walls better than 2.4/5 GHz. Used for sensors, smart buildings, and industrial IoT.",
     "wifi"),
    ("What is WPA2-PSK vs WPA2-Enterprise for companies?",
     "WPA2-PSK uses a shared password for all users — if one device is compromised, all are affected; no individual accountability. WPA2-Enterprise gives each user unique credentials via 802.1X/RADIUS, per-user encryption keys, audit logging, and role-based access. Enterprise networks MUST use WPA2-Enterprise.",
     "wifi_security"),

    # ── MICROSOFT-SPECIFIC NETWORKING ─────────────────────────────────
    ("What is Azure AD?",
     "Azure AD (now Microsoft Entra ID) is Microsoft's cloud identity and access management service. It provides SSO, MFA, conditional access, and integrates with Microsoft 365, VPN, and Wi-Fi (via certificate-based 802.1X or cloud RADIUS).",
     "intranet"),
    ("What is Intune?",
     "Microsoft Intune is a cloud-based MDM/MAM solution. It deploys Wi-Fi profiles, certificates, and VPN configurations to managed devices, enforces compliance policies, and can restrict non-compliant devices from corporate Wi-Fi via conditional access.",
     "intranet"),
    ("What is conditional access?",
     "Conditional access policies in Azure AD/Entra ID evaluate sign-in context (user, device, location, risk) and enforce controls: require MFA, block access, require compliant device. Used to secure Wi-Fi via NPS + Azure MFA integration.",
     "security"),
    ("What is Windows Autopilot?",
     "Windows Autopilot automates device provisioning: out-of-box setup, Azure AD join, Intune enrollment, and Wi-Fi/VPN profile deployment without IT physically touching the device. Users get a fully configured laptop shipped directly to them.",
     "intranet"),

    # ── PROGRAMMING (Python, general concepts) ────────────────────────
    ("What is a variable?",
     "A variable is a named reference to a value stored in memory. In Python, variables are dynamically typed — you don't declare a type, you just assign: x = 42. The type is inferred from the value.",
     "programming"),
    ("What is a function?",
     "A function is a reusable block of code defined with 'def' in Python. It takes parameters, executes a body, and optionally returns a value. Functions enable code reuse, modularity, and abstraction.",
     "programming"),
    ("What is a class?",
     "A class is a blueprint for creating objects. It bundles data (attributes) and behavior (methods) together. In Python: class Dog: def __init__(self, name): self.name = name. Instantiate with d = Dog('Rex').",
     "programming"),
    ("What is object-oriented programming?",
     "OOP organizes code into classes and objects. Core principles: encapsulation (bundling data+methods), inheritance (child classes extend parents), polymorphism (same interface, different behavior), and abstraction (hiding complexity).",
     "programming"),
    ("What is a decorator in Python?",
     "A decorator is a function that wraps another function to extend its behavior without modifying it. Syntax: @decorator above a function definition. Common uses: logging, authentication, caching, timing.",
     "programming"),
    ("What is a generator in Python?",
     "A generator is a function that uses 'yield' instead of 'return' to produce a sequence of values lazily. It maintains state between calls, using memory efficiently for large datasets. Created with 'def gen(): yield x' or generator expressions (x for x in range(10)).",
     "programming"),
    ("What is a list comprehension?",
     "A list comprehension is a concise way to create lists: [expr for item in iterable if condition]. Example: [x**2 for x in range(10) if x % 2 == 0] creates [0, 4, 16, 36, 64]. Faster and more Pythonic than equivalent for-loops.",
     "programming"),
    ("What is exception handling?",
     "Exception handling uses try/except blocks to catch and handle runtime errors gracefully. 'try' wraps risky code, 'except' catches specific exceptions, 'finally' runs cleanup code regardless, and 'raise' throws exceptions explicitly.",
     "programming"),
    ("What are f-strings?",
     "F-strings (formatted string literals) are Python 3.6+ strings prefixed with 'f' that allow inline expressions: f'Hello {name}, you are {age} years old'. They support format specs: f'{price:.2f}' and arbitrary expressions: f'{len(items)} items'.",
     "programming"),
    ("What is a virtual environment?",
     "A virtual environment is an isolated Python installation that keeps project dependencies separate. Create with 'python -m venv .venv', activate it, then pip install packages. Prevents version conflicts between projects.",
     "programming"),
    ("What is pip?",
     "pip is Python's package installer. Usage: 'pip install package_name' to install, 'pip freeze > requirements.txt' to export dependencies, 'pip install -r requirements.txt' to install from a file. Always use inside a virtual environment.",
     "programming"),
    ("What are type hints in Python?",
     "Type hints annotate function signatures and variables with expected types: def greet(name: str) -> str. They don't enforce types at runtime but enable static analysis with mypy/pyright, improve IDE autocomplete, and serve as documentation.",
     "programming"),
    ("What is a context manager?",
     "A context manager handles resource setup and teardown using 'with' statements. Example: 'with open(f) as fh:' ensures the file is closed automatically. Implement custom ones with __enter__/__exit__ methods or @contextmanager decorator.",
     "programming"),
    ("What is a lambda function?",
     "A lambda is an anonymous single-expression function: lambda x, y: x + y. Useful for short callbacks, sorting keys (sorted(items, key=lambda x: x.name)), and functional programming with map/filter. For complex logic, use regular def functions.",
     "programming"),
    ("What are *args and **kwargs?",
     "*args collects extra positional arguments into a tuple; **kwargs collects extra keyword arguments into a dict. def f(*args, **kwargs) accepts any arguments. Used in decorators, wrapper functions, and flexible APIs.",
     "programming"),
    ("What is a dataclass?",
     "A dataclass (from dataclasses import dataclass) auto-generates __init__, __repr__, __eq__ from class annotations. @dataclass class Point: x: float; y: float. Reduces boilerplate for data-holding classes. Supports defaults, frozen=True for immutability.",
     "programming"),
    ("What is async/await in Python?",
     "async/await enables asynchronous programming. 'async def' defines a coroutine, 'await' pauses it until a result is ready. Used with asyncio for concurrent I/O (HTTP requests, database queries) without threads. Run with asyncio.run(main()).",
     "programming"),
    ("What is recursion?",
     "Recursion is when a function calls itself to solve a problem by breaking it into smaller subproblems. Every recursive function needs a base case (stopping condition) and a recursive case. Example: factorial(n) = n * factorial(n-1), base: factorial(0) = 1.",
     "programming"),
    ("What is a dictionary in Python?",
     "A dictionary is a key-value mapping: d = {'name': 'Alice', 'age': 30}. Keys must be hashable (strings, numbers, tuples). O(1) average lookup time. Common methods: .get(), .items(), .keys(), .values(). Dict comprehensions: {k: v for k, v in pairs}.",
     "programming"),
    ("What is the difference between a list and a tuple?",
     "Lists are mutable (can be modified after creation) and use square brackets [1, 2, 3]. Tuples are immutable (fixed after creation) and use parentheses (1, 2, 3). Tuples are faster, hashable (usable as dict keys), and signal 'this should not change'.",
     "programming"),

    # ── GIT (version control) ─────────────────────────────────────────
    ("What is Git?",
     "Git is a distributed version control system that tracks changes to files. Each developer has a full copy of the repository history. Core concepts: commits (snapshots), branches (parallel development lines), merges (combining branches), and remotes (shared repos like GitHub).",
     "git"),
    ("How do I create a Git repository?",
     "Run 'git init' in your project folder to create a new repo, or 'git clone <url>' to copy an existing one. Then 'git add .' to stage files and 'git commit -m \"message\"' to save a snapshot. Set up a remote with 'git remote add origin <url>'.",
     "git"),
    ("What is a Git branch?",
     "A branch is a lightweight pointer to a commit, enabling parallel development. Create with 'git branch feature-x' or 'git checkout -b feature-x'. The main/master branch is the default. Merge back with 'git merge feature-x'. Delete merged branches with 'git branch -d feature-x'.",
     "git"),
    ("What is the difference between merge and rebase?",
     "Merge creates a merge commit that combines two branches, preserving full history. Rebase replays your commits on top of another branch, creating a linear history. Use merge for shared branches, rebase for local feature branches before merging. Never rebase published commits.",
     "git"),
    ("What is git stash?",
     "'git stash' temporarily saves uncommitted changes so you can switch branches cleanly. 'git stash pop' re-applies them. 'git stash list' shows saved stashes. Useful when you need to switch context without committing half-done work.",
     "git"),
    ("What is a pull request?",
     "A pull request (PR) is a request to merge your branch into another (usually main). It enables code review: teammates can comment, suggest changes, and approve before merging. PRs show the diff, run CI checks, and document why changes were made.",
     "git"),
    ("How do I undo a Git commit?",
     "'git revert <hash>' creates a new commit that undoes changes (safe for shared branches). 'git reset --soft HEAD~1' moves HEAD back but keeps changes staged. 'git reset --hard HEAD~1' discards changes entirely (destructive). Use revert for published commits, reset for local ones.",
     "git"),
    ("What is .gitignore?",
     "A .gitignore file tells Git which files/folders to exclude from tracking. Common patterns: __pycache__/, *.pyc, .env, node_modules/, .venv/, *.log. Place it in the repo root. Each line is a glob pattern. Use '!' to negate (include) a pattern.",
     "git"),
    ("What is git cherry-pick?",
     "'git cherry-pick <commit-hash>' applies a specific commit from one branch onto your current branch. Useful for backporting bug fixes or selectively moving changes without merging an entire branch.",
     "git"),
    ("What is git bisect?",
     "'git bisect' performs a binary search through commit history to find which commit introduced a bug. Start with 'git bisect start', mark good/bad commits, and Git narrows down to the culprit in O(log n) steps.",
     "git"),

    # ── ALGORITHMS & DATA STRUCTURES ──────────────────────────────────
    ("What is Big-O notation?",
     "Big-O describes how an algorithm's time or space grows with input size n. O(1) = constant, O(log n) = logarithmic, O(n) = linear, O(n log n) = linearithmic, O(n²) = quadratic, O(2ⁿ) = exponential. Measures worst-case scalability, ignoring constants.",
     "algorithms"),
    ("What is binary search?",
     "Binary search finds an element in a sorted array by repeatedly halving the search space. Compare target to middle element; if smaller, search left half; if larger, search right half. O(log n) time vs O(n) for linear search. Requires sorted input.",
     "algorithms"),
    ("What is BFS?",
     "Breadth-First Search explores a graph level by level using a queue. Visits all neighbors of a node before moving to the next depth level. O(V+E) time. Finds shortest path in unweighted graphs. Used for: shortest path, connected components, web crawling.",
     "algorithms"),
    ("What is DFS?",
     "Depth-First Search explores a graph by going as deep as possible before backtracking, using a stack (or recursion). O(V+E) time. Used for: topological sorting, cycle detection, maze solving, finding connected components.",
     "algorithms"),
    ("What is a hash table?",
     "A hash table maps keys to values using a hash function that computes an index into an array of buckets. Average O(1) lookup, insert, delete. Handles collisions via chaining or open addressing. Python's dict and set are hash tables.",
     "algorithms"),
    ("What is dynamic programming?",
     "Dynamic programming solves complex problems by breaking them into overlapping subproblems and caching results (memoization or tabulation). Example: Fibonacci — instead of O(2ⁿ) recursion, DP computes in O(n) by storing previously computed values.",
     "algorithms"),
    ("What is quicksort?",
     "Quicksort is a divide-and-conquer sorting algorithm. Pick a pivot, partition array into elements less than and greater than pivot, recursively sort both halves. Average O(n log n), worst case O(n²). In-place, not stable. Python's sorted() uses Timsort instead.",
     "algorithms"),
    ("What is a linked list?",
     "A linked list stores elements as nodes, each pointing to the next. Singly-linked: each node has data + next pointer. Doubly-linked: also has a prev pointer. O(1) insert/delete at head, O(n) access by index. Used when frequent insertions/deletions are needed.",
     "algorithms"),

    # ── DEBUGGING ─────────────────────────────────────────────────────
    ("How do I debug Python code?",
     "Use a debugger: 'import pdb; pdb.set_trace()' or Python 3.7+ 'breakpoint()'. In VS Code, set breakpoints and press F5. Step through with 'n' (next), 's' (step into), 'c' (continue), 'p var' (print). Also: print(), logging, and IDE debuggers.",
     "debugging"),
    ("What is a stack trace?",
     "A stack trace (traceback) shows the call chain when an exception occurs, from outermost to innermost frame. Read bottom-up: the last line shows the error type and message, above it the file/line/function where it happened. Essential for locating bugs.",
     "debugging"),
    ("What is logging in Python?",
     "The logging module provides leveled output: DEBUG, INFO, WARNING, ERROR, CRITICAL. Use logging.basicConfig(level=logging.DEBUG) to configure. Better than print() because you can control verbosity, format messages, write to files, and disable without removing code.",
     "debugging"),
    ("What is profiling?",
     "Profiling measures where your code spends time. Use cProfile: 'python -m cProfile script.py'. For line-by-line: line_profiler. For memory: memory_profiler. Identify bottlenecks before optimizing — measure, don't guess.",
     "debugging"),
    ("What are common Python error types?",
     "TypeError: wrong type operation. ValueError: right type, wrong value. KeyError: missing dict key. IndexError: list index out of range. AttributeError: missing attribute. ImportError: module not found. NameError: undefined variable. FileNotFoundError: path doesn't exist.",
     "debugging"),
    ("What is a memory leak?",
     "A memory leak occurs when a program holds references to objects no longer needed, preventing garbage collection. In Python: watch for circular references, global caches that grow unbounded, and closures capturing large objects. Use tracemalloc or objgraph to diagnose.",
     "debugging"),

    # ── TESTING ───────────────────────────────────────────────────────
    ("What is unit testing?",
     "Unit testing verifies individual functions or methods in isolation. Each test checks one behavior with known inputs and expected outputs. In Python, use pytest: define functions starting with 'test_', use assert statements, run with 'pytest tests/ -v'.",
     "testing"),
    ("What is the difference between unit and integration tests?",
     "Unit tests check individual components in isolation (with mocks for dependencies). Integration tests check how components work together (real database, real API calls). Unit tests are fast and numerous; integration tests are slower but catch interface bugs.",
     "testing"),
    ("What is mocking?",
     "Mocking replaces real objects with fake ones during testing to isolate the code under test. In Python: from unittest.mock import patch, MagicMock. @patch('module.function') replaces it with a mock. Verify calls with mock.assert_called_with().",
     "testing"),
    ("What is test coverage?",
     "Test coverage measures what percentage of your code is executed by tests. Run with 'pytest --cov=mypackage'. 100% coverage doesn't mean bug-free — it means every line ran, not that every edge case was tested. Aim for high coverage on critical paths.",
     "testing"),
    ("What is TDD?",
     "Test-Driven Development: write a failing test first, then write the minimum code to pass it, then refactor. Red-Green-Refactor cycle. Forces you to think about interfaces before implementation. Results in well-tested, modular code.",
     "testing"),
    ("What are pytest fixtures?",
     "Fixtures are reusable setup/teardown functions in pytest. Decorated with @pytest.fixture, they provide test data or resources. Use 'autouse=True' for automatic application. Scopes: function (default), class, module, session. Yield fixtures handle teardown after yield.",
     "testing"),

    # ── DATABASE ──────────────────────────────────────────────────────
    ("What is SQL?",
     "SQL (Structured Query Language) is the standard language for managing and querying relational databases. It supports statements like SELECT, INSERT, UPDATE, and DELETE to manipulate data, along with DDL commands like CREATE TABLE and ALTER TABLE to define schema.",
     "database"),
    ("What is the difference between relational and non-relational databases?",
     "Relational databases (MySQL, PostgreSQL) store data in structured tables with predefined schemas and use SQL for queries. Non-relational (NoSQL) databases (MongoDB, Redis) use flexible schemas like documents, key-value pairs, or graphs, optimizing for specific access patterns and horizontal scaling.",
     "database"),
    ("What is a database index?",
     "An index is a data structure (typically a B-tree or hash) that speeds up row lookups by column value. It trades extra storage and slower writes for dramatically faster reads. Create one with CREATE INDEX idx_name ON table(column).",
     "database"),
    ("What is database normalization?",
     "Normalization organizes tables to reduce redundancy and improve data integrity. Normal forms (1NF, 2NF, 3NF, BCNF) progressively eliminate partial and transitive dependencies. Over-normalizing can hurt read performance, so denormalization is sometimes used for analytics workloads.",
     "database"),
    ("What are ACID properties?",
     "ACID stands for Atomicity (all-or-nothing), Consistency (valid state transitions), Isolation (concurrent transactions don't interfere), and Durability (committed data survives crashes). These properties guarantee reliable transaction processing in relational databases.",
     "database"),
    ("What is a database transaction?",
     "A transaction is a sequence of operations executed as a single logical unit. It either fully completes (COMMIT) or fully rolls back (ROLLBACK). Transactions ensure data integrity even when multiple users modify the database concurrently.",
     "database"),
    ("What are SQL joins?",
     "Joins combine rows from two or more tables based on a related column. INNER JOIN returns matching rows from both tables. LEFT JOIN returns all rows from the left table plus matches. RIGHT JOIN is the reverse. FULL OUTER JOIN returns all rows from both tables.",
     "database"),
    ("What is an ORM?",
     "An ORM (Object-Relational Mapper) maps database tables to programming language objects, letting you query and manipulate data using code instead of raw SQL. Examples include SQLAlchemy for Python and Hibernate for Java. ORMs simplify development but can generate suboptimal queries.",
     "database"),
    ("What are the types of NoSQL databases?",
     "The four main types are: document stores (MongoDB) for JSON-like records, key-value stores (Redis) for simple lookups, column-family stores (Cassandra) for wide-row analytics, and graph databases (Neo4j) for highly connected data with relationship queries.",
     "database"),
    ("What is query optimization?",
     "Query optimization is the process of improving SQL performance by analyzing execution plans, adding appropriate indexes, rewriting inefficient queries, and avoiding full table scans. Tools like EXPLAIN help identify bottlenecks such as missing indexes or unnecessary joins.",
     "database"),

    # ── CLOUD ─────────────────────────────────────────────────────────
    ("What is cloud computing?",
     "Cloud computing delivers computing resources (servers, storage, databases, networking) over the internet on a pay-as-you-go basis. It eliminates the need to own and maintain physical data centers, offering elasticity, global reach, and reduced capital expenditure.",
     "cloud"),
    ("What is the difference between IaaS, PaaS, and SaaS?",
     "IaaS (Infrastructure as a Service) provides raw compute, storage, and networking (e.g., EC2). PaaS (Platform as a Service) adds managed runtimes and databases (e.g., Heroku, App Engine). SaaS (Software as a Service) delivers complete applications (e.g., Gmail, Salesforce).",
     "cloud"),
    ("What are AWS, Azure, and GCP?",
     "AWS (Amazon Web Services), Azure (Microsoft), and GCP (Google Cloud Platform) are the three largest public cloud providers. Each offers hundreds of services for compute, storage, AI, databases, and more, with global data center regions and pay-per-use pricing.",
     "cloud"),
    ("What are containers in cloud computing?",
     "Containers package an application with its dependencies into a lightweight, portable unit that runs consistently across environments. Docker is the most popular container runtime. Containers share the host OS kernel, making them faster and more efficient than virtual machines.",
     "cloud"),
    ("What is serverless computing?",
     "Serverless lets you run code without provisioning or managing servers. The cloud provider automatically scales and charges per execution (e.g., AWS Lambda, Azure Functions). You write functions triggered by events like HTTP requests, queues, or schedules.",
     "cloud"),
    ("What is auto-scaling?",
     "Auto-scaling automatically adjusts the number of running instances based on demand metrics like CPU usage or request count. It scales out (adds instances) during traffic spikes and scales in (removes instances) during lulls, optimizing cost and performance.",
     "cloud"),
    ("What is cloud security?",
     "Cloud security encompasses identity and access management (IAM), network isolation (VPCs, security groups), encryption at rest and in transit, compliance certifications, and shared responsibility models where the provider secures infrastructure and the customer secures their data and configurations.",
     "cloud"),
    ("What is a CDN?",
     "A CDN (Content Delivery Network) caches static assets (images, CSS, JS) at edge servers distributed globally, reducing latency by serving content from the location nearest to the user. Popular CDNs include CloudFront, Cloudflare, and Akamai.",
     "cloud"),
    ("What are microservices?",
     "Microservices architecture decomposes an application into small, independently deployable services, each owning its own data and communicating via APIs or message queues. This enables teams to develop, deploy, and scale services independently, though it adds operational complexity.",
     "cloud"),
    ("What is cloud storage?",
     "Cloud storage provides scalable, durable object or block storage accessible over the internet. Object stores like S3 hold unstructured data (files, images). Block storage (EBS) provides raw volumes for VMs. File storage (EFS) offers shared POSIX-compliant file systems.",
     "cloud"),

    # ── LINUX ─────────────────────────────────────────────────────────
    ("What is Linux?",
     "Linux is an open-source, Unix-like operating system kernel created by Linus Torvalds in 1991. Combined with GNU tools and various distributions (Ubuntu, Fedora, Arch), it powers most servers, cloud infrastructure, Android devices, and supercomputers worldwide.",
     "linux"),
    ("What are basic Linux commands?",
     "Essential commands include: ls (list files), cd (change directory), pwd (print working directory), cp/mv/rm (copy/move/remove files), cat/less (view files), grep (search text), find (locate files), and man (read manuals).",
     "linux"),
    ("How do Linux file permissions work?",
     "Each file has permissions for owner, group, and others, with read (r=4), write (w=2), and execute (x=1) bits. Use chmod to change permissions (e.g., chmod 755 file). Use chown to change ownership. ls -l shows permissions like -rwxr-xr-x.",
     "linux"),
    ("What are Linux package managers?",
     "Package managers install, update, and remove software. Debian/Ubuntu use apt (apt install package). Red Hat/Fedora use dnf or yum. Arch uses pacman. Alpine uses apk. They resolve dependencies automatically and pull from curated repositories.",
     "linux"),
    ("What is shell scripting?",
     "Shell scripting automates tasks by writing sequences of commands in a file (typically Bash). Scripts support variables, loops, conditionals, functions, and piping. Start with #!/bin/bash, make executable with chmod +x, and run with ./script.sh.",
     "linux"),
    ("What are cron jobs?",
     "Cron is a time-based scheduler in Linux. Edit crontab with 'crontab -e' and define schedules using five fields: minute, hour, day-of-month, month, day-of-week. Example: '0 2 * * * /path/script.sh' runs a script daily at 2 AM.",
     "linux"),
    ("What is systemd?",
     "systemd is the default init system and service manager on most modern Linux distributions. It manages service lifecycle (start, stop, restart, enable at boot) using unit files. Key commands: systemctl start/stop/status/enable service_name.",
     "linux"),
    ("What is SSH?",
     "SSH (Secure Shell) provides encrypted remote access to Linux systems. Connect with 'ssh user@host'. Use key-based authentication (ssh-keygen) instead of passwords for security. SCP and SFTP transfer files over SSH. Configure via ~/.ssh/config.",
     "linux"),
    ("What are environment variables in Linux?",
     "Environment variables store system-wide or user-specific configuration. Set temporarily with export VAR=value, permanently in ~/.bashrc or /etc/environment. Common ones: PATH (executable search paths), HOME (user directory), LANG (locale). View with printenv or echo $VAR.",
     "linux"),
    ("How does Linux process management work?",
     "Processes are managed with ps (list), top/htop (monitor), kill (terminate by PID), and jobs/bg/fg (job control). Every process has a PID and parent PID. Signals like SIGTERM (15) gracefully stop processes; SIGKILL (9) forces termination.",
     "linux"),

    # ── WEB DEVELOPMENT ───────────────────────────────────────────────
    ("What are HTML and CSS?",
     "HTML (HyperText Markup Language) defines the structure and content of web pages using elements like headings, paragraphs, links, and forms. CSS (Cascading Style Sheets) controls visual presentation — layout, colors, fonts, and responsive design — separating content from styling.",
     "web_development"),
    ("What are JavaScript fundamentals?",
     "JavaScript is the programming language of the web, running in browsers and on servers (Node.js). Key concepts include variables (let/const), functions, DOM manipulation, event handling, promises for async operations, and ES6+ features like arrow functions and destructuring.",
     "web_development"),
    ("What is a REST API?",
     "REST (Representational State Transfer) is an architectural style for web APIs using HTTP methods on resources identified by URLs. It follows principles like statelessness, uniform interface, and resource-based URIs. Responses are typically JSON. Example: GET /api/users returns a user list.",
     "web_development"),
    ("What are HTTP methods?",
     "The main HTTP methods are: GET (retrieve data), POST (create resource), PUT (replace resource), PATCH (partial update), and DELETE (remove resource). HEAD retrieves headers only, and OPTIONS describes available methods. These map to CRUD operations in REST APIs.",
     "web_development"),
    ("What is the difference between frontend and backend?",
     "Frontend (client-side) is what users see and interact with — HTML, CSS, JavaScript running in the browser. Backend (server-side) handles business logic, database access, and authentication — using languages like Python, Java, or Node.js. They communicate via HTTP/APIs.",
     "web_development"),
    ("What are web frameworks?",
     "Web frameworks provide structure and tools for building web applications. Backend frameworks include Flask, Django (Python), Express (Node.js), and Spring (Java). Frontend frameworks include React, Vue, and Angular. They handle routing, templating, and common patterns.",
     "web_development"),
    ("What is responsive design?",
     "Responsive design makes web pages adapt to different screen sizes using CSS media queries, flexible grids, and fluid images. Mobile-first design starts with small screens. Modern CSS tools like flexbox and grid simplify responsive layouts without JavaScript.",
     "web_development"),
    ("What is web performance optimization?",
     "Key techniques include minifying CSS/JS, compressing images, using CDNs, enabling browser caching, lazy-loading resources, reducing HTTP requests, and code-splitting. Tools like Lighthouse audit performance. Core Web Vitals (LCP, FID, CLS) measure real user experience.",
     "web_development"),
    ("What are cookies and sessions?",
     "Cookies are small key-value pairs stored in the browser, sent with every HTTP request to the same domain. Sessions store user state server-side, identified by a session ID cookie. Cookies have attributes like HttpOnly, Secure, SameSite, and expiration to control security and scope.",
     "web_development"),
    ("What are basic web security practices?",
     "Essential web security includes: validating and sanitizing all user input, using HTTPS everywhere, setting Content-Security-Policy headers, preventing XSS by escaping output, using CSRF tokens for state-changing requests, and keeping dependencies updated for known vulnerability patches.",
     "web_development"),

    # ── DATA STRUCTURES ───────────────────────────────────────────────
    ("What is the difference between arrays and linked lists?",
     "Arrays store elements in contiguous memory, offering O(1) random access but O(n) insertion/deletion. Linked lists use nodes with pointers, giving O(1) insertion/deletion at known positions but O(n) access. Arrays have better cache locality; linked lists handle dynamic sizing naturally.",
     "data_structures"),
    ("What is a stack?",
     "A stack is a Last-In-First-Out (LIFO) data structure supporting push (add to top) and pop (remove from top) in O(1) time. Use cases include function call stacks, undo operations, expression parsing, and depth-first search. In Python, use a list with append() and pop().",
     "data_structures"),
    ("What is a queue?",
     "A queue is a First-In-First-Out (FIFO) data structure supporting enqueue (add to back) and dequeue (remove from front) in O(1) time. Use cases include BFS, task scheduling, and buffering. In Python, use collections.deque for efficient O(1) operations on both ends.",
     "data_structures"),
    ("What is a tree data structure?",
     "A tree is a hierarchical structure with a root node and child nodes forming a parent-child relationship. Each node has zero or more children. Trees have no cycles. Common types include binary trees, B-trees, and tries. Trees model filesystems, DOM, and organizational hierarchies.",
     "data_structures"),
    ("What is a binary search tree?",
     "A BST is a binary tree where each node's left children are smaller and right children are larger. This property enables O(log n) search, insert, and delete on average. Unbalanced BSTs degrade to O(n). Self-balancing variants like AVL and red-black trees guarantee O(log n).",
     "data_structures"),
    ("What is a heap data structure?",
     "A heap is a complete binary tree satisfying the heap property: in a min-heap, each parent is smaller than its children; in a max-heap, larger. Heaps support O(log n) insert and extract-min/max, and O(1) peek. Used for priority queues and heap sort. Python provides heapq module.",
     "data_structures"),
    ("What is a graph data structure?",
     "A graph consists of vertices (nodes) connected by edges. Graphs can be directed or undirected, weighted or unweighted. Represented as adjacency lists or matrices. Algorithms include BFS, DFS, Dijkstra (shortest path), and Kruskal/Prim (minimum spanning tree).",
     "data_structures"),
    ("What is a hash map?",
     "A hash map (dictionary in Python) stores key-value pairs using a hash function to compute bucket indices. It provides average O(1) lookup, insert, and delete. Collisions are handled by chaining or open addressing. Hash maps trade memory for speed.",
     "data_structures"),
    ("What is a trie?",
     "A trie (prefix tree) is a tree where each node represents a character of a string. Paths from root to marked nodes form stored words. Tries enable O(m) lookup (m = word length) and efficient prefix search. Used in autocomplete, spell checkers, and IP routing tables.",
     "data_structures"),
    ("What is a set data structure?",
     "A set is an unordered collection of unique elements, typically backed by a hash table. It supports O(1) average membership testing, insertion, and deletion. Set operations include union, intersection, difference, and symmetric difference. In Python, use set() or curly braces.",
     "data_structures"),

    # ── MACHINE LEARNING ──────────────────────────────────────────────
    ("What is machine learning?",
     "Machine learning is a subset of AI where systems learn patterns from data instead of being explicitly programmed. Models improve through experience by optimizing an objective function. The three main paradigms are supervised learning, unsupervised learning, and reinforcement learning.",
     "machine_learning"),
    ("What is the difference between supervised and unsupervised learning?",
     "Supervised learning trains on labeled data (input-output pairs) to predict outputs for new inputs — used for classification and regression. Unsupervised learning finds patterns in unlabeled data — used for clustering, dimensionality reduction, and anomaly detection.",
     "machine_learning"),
    ("What are neural networks?",
     "Neural networks are computational models inspired by biological neurons. They consist of layers of interconnected nodes that apply weights, biases, and activation functions to transform inputs into outputs. Deep networks with many layers can learn complex, hierarchical representations.",
     "machine_learning"),
    ("What is overfitting?",
     "Overfitting occurs when a model memorizes training data instead of learning generalizable patterns, performing well on training data but poorly on unseen data. Combat it with regularization (L1/L2), dropout, early stopping, data augmentation, or using a simpler model architecture.",
     "machine_learning"),
    ("What are training, validation, and test sets?",
     "Data is split into three sets: training (60-80%) for learning parameters, validation (10-20%) for tuning hyperparameters and detecting overfitting, and test (10-20%) for final unbiased evaluation. Never tune on the test set — it must remain unseen until final assessment.",
     "machine_learning"),
    ("What is gradient descent?",
     "Gradient descent is an optimization algorithm that iteratively adjusts model parameters in the direction that minimizes the loss function. The gradient points uphill; we step opposite to it. Variants include batch, stochastic (SGD), and mini-batch gradient descent. Learning rate controls step size.",
     "machine_learning"),
    ("What is feature engineering?",
     "Feature engineering transforms raw data into informative inputs for ML models. Techniques include normalization, one-hot encoding categorical variables, creating interaction features, handling missing values, and extracting domain-specific signals. Good features often matter more than complex models.",
     "machine_learning"),
    ("What is the difference between classification and regression?",
     "Classification predicts discrete categories (spam vs. not spam, digit recognition) using algorithms like logistic regression, SVMs, and decision trees. Regression predicts continuous values (house prices, temperature) using linear regression, polynomial regression, or neural networks.",
     "machine_learning"),
    ("What is clustering?",
     "Clustering groups similar data points without labels. K-means partitions data into k clusters by minimizing within-cluster distances. DBSCAN finds density-based clusters of arbitrary shape. Hierarchical clustering builds dendrograms. Evaluate with silhouette score or elbow method.",
     "machine_learning"),
    ("What are model evaluation metrics?",
     "Classification metrics include accuracy, precision, recall, F1-score, and AUC-ROC. Regression metrics include MSE (mean squared error), RMSE, MAE, and R-squared. Choose metrics based on the problem: precision for spam filters, recall for medical diagnostics, RMSE for forecasting.",
     "machine_learning"),

    # ── DEVOPS ────────────────────────────────────────────────────────
    ("What is DevOps?",
     "DevOps is a culture and set of practices that unifies software development (Dev) and IT operations (Ops) to shorten the development lifecycle and deliver high-quality software continuously. Key principles include automation, collaboration, continuous improvement, and shared responsibility.",
     "devops"),
    ("What is CI/CD?",
     "CI (Continuous Integration) automatically builds and tests code on every commit. CD (Continuous Delivery) automates deployment to staging; Continuous Deployment pushes to production automatically. Tools include GitHub Actions, Jenkins, GitLab CI, and CircleCI. CI/CD catches bugs early and speeds releases.",
     "devops"),
    ("What is Docker?",
     "Docker is a platform for building, shipping, and running applications in containers. A Dockerfile defines the image; docker build creates it; docker run starts a container. Images are stored in registries like Docker Hub. Compose orchestrates multi-container apps with docker-compose.yml.",
     "devops"),
    ("What is Kubernetes?",
     "Kubernetes (K8s) is an open-source container orchestration platform that automates deployment, scaling, and management of containerized applications. Key concepts include Pods, Services, Deployments, and Ingress. It handles load balancing, self-healing, rolling updates, and secret management.",
     "devops"),
    ("What is monitoring in DevOps?",
     "Monitoring tracks system health, performance, and availability using metrics, logs, and traces. Tools like Prometheus collect metrics, Grafana visualizes dashboards, and alerting notifies on-call engineers of anomalies. The three pillars of observability are metrics, logs, and traces.",
     "devops"),
    ("What is logging in DevOps?",
     "Centralized logging aggregates log output from all services into a searchable system. The ELK stack (Elasticsearch, Logstash, Kibana) and Loki/Grafana are popular solutions. Structured logging (JSON format) with correlation IDs makes it easier to trace requests across microservices.",
     "devops"),
    ("What is Infrastructure as Code?",
     "Infrastructure as Code (IaC) manages servers, networks, and cloud resources through version-controlled configuration files instead of manual setup. Tools include Terraform (multi-cloud), CloudFormation (AWS), and Pulumi. IaC enables reproducible, auditable, and automated infrastructure provisioning.",
     "devops"),
    ("What is configuration management?",
     "Configuration management ensures systems are configured consistently and automatically. Tools like Ansible, Chef, and Puppet define desired state in code and enforce it across servers. Ansible uses agentless SSH and YAML playbooks, making it popular for its simplicity.",
     "devops"),
    ("What are deployment strategies?",
     "Common deployment strategies include: rolling (gradually replace instances), blue-green (swap between two identical environments), canary (route a small percentage of traffic to the new version), and feature flags (toggle features without deploying). Each balances risk, speed, and rollback capability.",
     "devops"),
    ("What is incident response?",
     "Incident response is the process of detecting, responding to, and recovering from production issues. It includes alerting, triage, mitigation, root cause analysis, and blameless postmortems. On-call rotations and runbooks ensure teams can respond quickly and learn from failures.",
     "devops"),

    # ── PYTHON ADVANCED ───────────────────────────────────────────────
    ("What are Python metaclasses?",
     "Metaclasses are classes of classes — they control class creation. type is the default metaclass. Define a custom metaclass by inheriting from type and overriding __new__ or __init_subclass__. Use cases include ORM field registration, API validation, and singleton patterns.",
     "python_advanced"),
    ("What are Python descriptors?",
     "Descriptors are objects that define __get__, __set__, or __delete__ methods to customize attribute access. They power property, classmethod, and staticmethod. Data descriptors (with __set__) take precedence over instance __dict__. Non-data descriptors (only __get__) do not.",
     "python_advanced"),
    ("What are __slots__ in Python?",
     "__slots__ declares a fixed set of attribute names for a class, replacing the per-instance __dict__ with a compact, memory-efficient struct. This reduces memory usage by 40-50% for classes with many instances. Slots prevent dynamic attribute addition unless __dict__ is included in __slots__.",
     "python_advanced"),
    ("What is the Python GIL?",
     "The Global Interpreter Lock (GIL) in CPython allows only one thread to execute Python bytecode at a time, limiting true parallelism for CPU-bound tasks. Use multiprocessing for CPU parallelism or asyncio for I/O concurrency. The GIL simplifies memory management but is a known bottleneck.",
     "python_advanced"),
    ("What is the difference between multiprocessing and threading in Python?",
     "Threading runs multiple threads in one process sharing memory, limited by the GIL for CPU tasks but good for I/O-bound work. Multiprocessing spawns separate processes with their own memory and GIL, enabling true CPU parallelism. Use concurrent.futures for a unified high-level interface.",
     "python_advanced"),
    ("What is Python itertools?",
     "itertools provides memory-efficient iterator building blocks. Key functions: chain (concatenate iterables), product (Cartesian product), combinations/permutations (combinatorics), groupby (group consecutive elements), islice (slice iterators), and count/cycle/repeat (infinite iterators).",
     "python_advanced"),
    ("What is Python functools?",
     "functools provides higher-order function utilities. lru_cache memoizes function results. partial freezes some arguments. reduce applies a function cumulatively. wraps preserves decorated function metadata. total_ordering fills in comparison methods from __eq__ and one ordering method.",
     "python_advanced"),
    ("What is Python contextlib?",
     "contextlib simplifies context manager creation. @contextmanager turns a generator function (with a single yield) into a context manager. suppress() ignores specified exceptions. ExitStack manages dynamic numbers of context managers. nullcontext() is a no-op context manager for conditional use.",
     "python_advanced"),
    ("What is Python pathlib?",
     "pathlib provides object-oriented filesystem path handling, replacing os.path. Path objects support / operator for joining, .read_text()/.write_text() for file I/O, .glob() for pattern matching, .mkdir(parents=True) for directory creation, and .suffix/.stem for name parsing.",
     "python_advanced"),
    ("What are advanced features of Python typing?",
     "Advanced typing features include TypeVar and Generic for generic classes, Protocol for structural subtyping (duck typing), Literal for exact value types, TypeGuard for narrowing, ParamSpec for decorator typing, and TypeAlias for readable type definitions. Use mypy or pyright for static checking.",
     "python_advanced"),

    # ── GENERAL / META ────────────────────────────────────────────────
    ("What is libaix?",
     "libaix is a neural network built from scratch using only NumPy. It supports multiple activations, optimizers, and can learn to classify text about networking, security, programming, algorithms, and more.",
     "general"),
    ("Who made libaix?",
     "libaix was built as an open-source project to demonstrate neural networks from scratch without ML frameworks, hosted on GitHub.",
     "general"),
    ("What can this AI do?",
     "I can answer questions about networking, security, programming, algorithms, Git, debugging, testing, Wi-Fi, and more. I combine a neural network classifier with a reasoning engine for intelligent answers. Say 'research <topic>' to teach me new things!",
     "general"),
    ("Hello",
     "Hello! I'm libaix, a neural network built from scratch with NumPy. I know about networking, security, programming, algorithms, Git, debugging, testing, and more. Ask me anything!",
     "general"),
    ("Help",
     "I can answer questions about: networking (TCP/IP, OSI, routing), security (firewalls, encryption, zero trust), programming (Python, OOP, decorators, async), algorithms (Big-O, sorting, search), Git (branches, merge, rebase), debugging (pdb, logging, profiling), and testing (pytest, mocking, TDD). Just ask!",
     "general"),
]


def get_domains() -> list[str]:
    """Return sorted list of unique domain tags."""
    return sorted(set(domain for _, _, domain in KNOWLEDGE))


def get_questions() -> list[str]:
    return [q for q, _, _ in KNOWLEDGE]


def get_answers() -> list[str]:
    return [a for _, a, _ in KNOWLEDGE]


def get_domain_labels() -> list[str]:
    return [d for _, _, d in KNOWLEDGE]


def load_extra_knowledge(path: str | Path) -> list[tuple[str, str, str]]:
    """Load additional Q&A entries from a JSON file.

    Expected format: [{"question": "...", "answer": "...", "domain": "..."}]
    """
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return [(e["question"], e["answer"], e["domain"]) for e in data]
